/**
 * Seed: Categorias, Subcategorias e Procedimentos — Regulação Assistencial
 * Monitora Saúde — backend/prisma/seeds/fila-seed.ts
 *
 * Execução: npx ts-node backend/prisma/seeds/fila-seed.ts
 * Idempotente: pode ser executado múltiplas vezes sem duplicar dados (upsert).
 */

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// ─── Estrutura de dados ────────────────────────────────────────────────────

const SEED_DATA = [

  // 1. PROCEDIMENTOS COM FINALIDADE DIAGNÓSTICA
  {
    codigo: 'DIAGNOSTICO',
    nome: 'Procedimentos com Finalidade Diagnóstica',
    descricao: 'Exames e procedimentos realizados para diagnóstico de condições de saúde',
    subCategorias: [
      {
        codigo: 'DIAG_LAB',
        nome: 'Diagnóstico Laboratorial',
        procedimentos: [
          'Hemograma completo com diferencial',
          'Glicemia em jejum',
          'Hemoglobina glicada (HbA1c)',
          'Glicemia pós-prandial (2 horas)',
          'Colesterol total e frações (HDL, LDL, VLDL)',
          'Triglicerídeos',
          'Ureia',
          'Creatinina sérica',
          'Ácido úrico',
          'TSH (Tireotropina)',
          'T4 livre (Tiroxina livre)',
          'T3 total',
          'Urina tipo 1 (EAS / Urinálise)',
          'Urocultura com antibiograma',
          'PSA total e livre (Antígeno Prostático Específico)',
          'Beta-HCG quantitativo',
          'Coproparasitológico (EPF)',
          'Cultura de secreções (com antibiograma)',
          'PCR (Proteína C Reativa) quantitativa',
          'VHS (Velocidade de Hemossedimentação)',
          'Coagulograma completo (TP, TTPa, INR)',
          'Ionograma (Sódio, Potássio, Cloro)',
          'TGO / AST (Aspartato aminotransferase)',
          'TGP / ALT (Alanina aminotransferase)',
          'Gama GT (Gamaglutamiltransferase)',
          'Fosfatase alcalina',
          'Bilirrubinas total e frações',
          'Albumina sérica',
          'Proteínas totais e frações',
          'HIV 1 e 2 (sorologia)',
          'Hepatite B — HBsAg (antígeno de superfície)',
          'Hepatite B — Anti-HBs (anticorpo de superfície)',
          'Hepatite B — Anti-HBc total',
          'Hepatite C — Anti-HCV',
          'Sífilis — VDRL quantitativo',
          'Sífilis — FTA-Abs (confirmatório)',
          'Toxoplasmose IgM e IgG',
          'Rubéola IgM e IgG',
          'Citomegalovírus (CMV) IgM e IgG',
          'Ferro sérico e TIBC',
          'Ferritina sérica',
          'Vitamina D (25-OH vitamina D)',
          'Vitamina B12 (Cobalamina)',
          'Ácido fólico sérico',
          'Lactato desidrogenase (LDH)',
          'Amilase sérica',
          'Lipase sérica',
          'Dengue NS1 + IgM/IgG (teste rápido ou ELISA)',
          'Sorologia para Chagas (IgG)',
          'Hemoculturas (2 amostras)',
          'Parasitológico de fezes com pesquisa de H. pylori',
          'Antígeno de H. pylori nas fezes',
          'Pesquisa de bacilo álcool-ácido resistente (BAAR — 3 amostras)',
          'Curva glicêmica (GTT 75g)',
          'Reticulócitos',
          'Plaquetas (contagem isolada)',
          'Leucograma diferencial',
          'Eletrólitos urinários (sódio, potássio urinário)',
          'Microalbuminúria (relação albumina/creatinina)',
          'Clearance de creatinina (TFG estimada)',
          'PTH intacto (Paratormônio)',
          'Calcitonina',
          'CEA (Antígeno carcinoembrionário)',
          'CA 125 (marcador tumoral)',
          'CA 15-3 (marcador tumoral)',
          'CA 19-9 (marcador tumoral)',
          'AFP (Alfafetoproteína)',
          'Beta-2 microglobulina',
          'Fator reumatoide',
          'Anti-CCP (anticorpo antipeptídeo citrulinado)',
          'FAN (Fator antinuclear)',
          'Anti-DNA dupla fita',
          'ANCA (anticorpo anticitoplasma de neutrófilos)',
          'Complemento C3 e C4',
          'Imunoglobulinas (IgA, IgM, IgG)',
          'Eletroforese de proteínas séricas',
          'Espermograma',
          'Prolactina',
          'FSH e LH',
          'Estradiol',
          'Progesterona',
          'Testosterona total e livre',
          'Cortisol basal',
          'ACTH (hormônio adrenocorticotrófico)',
          'Hormônio do crescimento (GH)',
          'IGF-1 (Somatomedina C)',
          'Gasometria arterial',
          'Lactato venoso',
        ],
      },
      {
        codigo: 'DIAG_ANATOMO',
        nome: 'Diagnóstico Anatomopatológico',
        procedimentos: [
          'Citologia oncótica cérvico-vaginal (Papanicolau)',
          'Biópsia de pele e tecido subcutâneo',
          'Biópsia de mucosa gástrica (endoscópica)',
          'Biópsia de colo uterino (punch/LEEP)',
          'Biópsia de próstata (sistemática transretal)',
          'Biópsia de mama (core biopsy / mamotomia)',
          'Biópsia de linfonodo (excisional)',
          'Biópsia de fígado (percutânea)',
          'Biópsia de rim (percutânea)',
          'Biópsia de pulmão (transtorácica)',
          'Biópsia de medula óssea (aspirado + biópsia)',
          'Biópsia de tireoide (guiada por USS)',
          'Biópsia de mucosa de cólon (colonoscópica)',
          'Biópsia de mucosa retal',
          'Biópsia de vesícula biliar / vias biliares',
          'Citologia de escarro (pesquisa de células malignas)',
          'Citologia de líquido pleural',
          'Citologia de líquido ascítico (peritoneal)',
          'Citologia de líquido cefalorraquidiano',
          'PAAF — mama (Punção Aspirativa por Agulha Fina)',
          'PAAF — tireoide',
          'PAAF — linfonodo',
          'PAAF — glândula parótida',
          'Histopatológico de peça cirúrgica (análise geral)',
          'Imunohistoquímica (painel básico)',
          'Imunofluorescência direta (pele/rim)',
          'Hibridização in situ (FISH/ISH)',
          'Citogenética (cariótipo convencional)',
          'Análise molecular / PCR em tecido',
        ],
      },
      {
        codigo: 'DIAG_RAIO_X',
        nome: 'Diagnóstico por Raio X',
        procedimentos: [
          'Radiografia de tórax PA e perfil',
          'Radiografia de abdome (simples)',
          'Radiografia de coluna cervical AP, P e oblíquas',
          'Radiografia de coluna torácica AP e P',
          'Radiografia de coluna lombar AP, P e oblíquas',
          'Radiografia de coluna lombossacra com funcional',
          'Radiografia de bacia (pelve) AP',
          'Radiografia de quadril unilateral',
          'Radiografia de fêmur',
          'Radiografia de joelho AP e P',
          'Radiografia de perna (tíbia e fíbula)',
          'Radiografia de tornozelo AP e P',
          'Radiografia de pé AP, P e oblíqua',
          'Radiografia de ombro AP e Y-view',
          'Radiografia de cotovelo AP e P',
          'Radiografia de antebraço AP e P',
          'Radiografia de punho AP e P',
          'Radiografia de mão AP e oblíqua',
          'Radiografia de crânio AP e P',
          'Radiografia de seios da face (Waters e Caldwell)',
          'Radiografia de ossos faciais',
          'Radiografia de órbitas',
          'Radiografia de mandíbula (panorâmica dentária)',
          'Mamografia bilateral com incidências adicionais',
          'Densitometria óssea (DXA) — coluna e fêmur',
          'Uretrocistografia retrógrada e miccional',
          'Urografia excretora (com contraste EV)',
          'Histerossalpingografia',
          'Trânsito esofagogastroduodenal (com contraste oral)',
          'Enema opaco (clister opaco)',
          'Colangiografia intraoperatória',
          'Flebografia (venografia de membros)',
          'Arteriografia (angiografia convencional)',
          'Radiografia de esterno',
          'Radiografia de clavícula',
          'Radiografia de calcâneo',
        ],
      },
      {
        codigo: 'DIAG_USS',
        nome: 'Diagnóstico por Ultrassonografia (USS)',
        procedimentos: [
          'Ultrassonografia de abdome total',
          'Ultrassonografia de abdome superior',
          'Ultrassonografia de abdome inferior (pelve feminina)',
          'Ultrassonografia transvaginal',
          'Ultrassonografia obstétrica — morfológica 1º trimestre',
          'Ultrassonografia obstétrica — morfológica 2º trimestre',
          'Ultrassonografia obstétrica — 3º trimestre e biometria',
          'Ultrassonografia obstétrica com Doppler (perfil biofísico)',
          'Ultrassonografia de mama bilateral',
          'Ultrassonografia de tireoide e paratireoides',
          'Ultrassonografia de rins, ureteres e bexiga',
          'Ultrassonografia de próstata transabdominal',
          'Ultrassonografia de próstata transretal',
          'Ultrassonografia de bolsa escrotal e testículos',
          'Ultrassonografia de partes moles (superficial)',
          'Ultrassonografia de articulações (ombro, joelho, quadril)',
          'Ultrassonografia de quadril neonatal (luxação)',
          'Ecocardiograma transtorácico (adulto)',
          'Ecocardiograma transtorácico pediátrico / fetal',
          'Ecocardiograma com Doppler colorido',
          'Doppler de carótidas e vertebrais (duplex scan)',
          'Doppler venoso de membros inferiores (TVP)',
          'Doppler arterial de membros inferiores',
          'Doppler arterial de membros superiores',
          'Doppler transcraniano',
          'Ultrassonografia de glândulas salivares',
          'Ultrassonografia de linfonodos cervicais / axilares',
          'Ultrassonografia transfontanela (neonatal)',
          'Elastografia hepática (FibroScan)',
          'Ultrassonografia intraoperatória',
          'Punção guiada por ultrassonografia (aspirado)',
          'Biópsia guiada por ultrassonografia',
        ],
      },
      {
        codigo: 'DIAG_TOMO',
        nome: 'Diagnóstico por Tomografia',
        procedimentos: [
          'Tomografia computadorizada de crânio sem contraste',
          'Tomografia computadorizada de crânio com contraste',
          'Tomografia de crânio com e sem contraste',
          'Tomografia de tórax (TCAR — alta resolução)',
          'Tomografia de tórax com contraste',
          'Angiotomografia pulmonar (TEP)',
          'Tomografia de abdome e pelve sem contraste',
          'Tomografia de abdome e pelve com contraste',
          'Tomografia de coluna cervical',
          'Tomografia de coluna torácica',
          'Tomografia de coluna lombar',
          'Tomografia de face e seios da face',
          'Tomografia de ossos da face e órbitas',
          'Tomografia de mastoide e osso temporal',
          'Tomografia de bacia e quadril',
          'Tomografia de joelho',
          'Tomografia de tornozelo e pé',
          'Tomografia de ombro',
          'Tomografia de cotovelo',
          'Tomografia de punho e mão',
          'Angiotomografia de coronárias (escore de cálcio + angiografia)',
          'Angiotomografia de aorta (torácica e/ou abdominal)',
          'Angiotomografia cerebral',
          'Angiotomografia de membros inferiores',
          'Tomografia de pescoço e laringe',
          'Tomografia de glândulas adrenais',
          'Colonoscopia virtual (colonografia por TC)',
          'Tomografia de corpo inteiro (estadiamento oncológico)',
          'Biópsia guiada por tomografia computadorizada',
          'Perfusão cerebral por tomografia',
        ],
      },
      {
        codigo: 'DIAG_RESSOM',
        nome: 'Diagnóstico por Ressonância Magnética',
        procedimentos: [
          'Ressonância magnética de crânio',
          'Ressonância magnética de crânio com contraste',
          'Ressonância magnética de sela túrcica (hipófise)',
          'Ressonância magnética de coluna cervical',
          'Ressonância magnética de coluna torácica',
          'Ressonância magnética de coluna lombar',
          'Ressonância magnética de coluna lombossacra',
          'Ressonância magnética de joelho',
          'Ressonância magnética de ombro',
          'Ressonância magnética de quadril',
          'Ressonância magnética de tornozelo e pé',
          'Ressonância magnética de punho e mão',
          'Ressonância magnética de cotovelo',
          'Ressonância magnética de abdome',
          'Ressonância magnética de fígado e vias biliares (colangioRM)',
          'Ressonância magnética de pelve feminina',
          'Ressonância magnética de próstata (multiparamétrica)',
          'Ressonância magnética de mama bilateral',
          'Ressonância magnética de pescoço',
          'Ressonância magnética de órbitas',
          'Ressonância magnética de osso temporal / ouvido interno',
          'Angiorressonância cerebral',
          'Angiorressonância de aorta torácica',
          'Angiorressonância de aorta abdominal e ramos',
          'Angiorressonância de membros inferiores',
          'Ressonância cardíaca (cinerressonância)',
          'Perfusão e difusão cerebral por RM',
          'Espectroscopia de prótons por RM',
          'Ressonância magnética funcional (fRM) — pré-cirúrgico',
          'Ressonância magnética fetal',
          'Enterorressonância (RM de intestino delgado)',
          'Ressonância magnética de partes moles',
        ],
      },
      {
        codigo: 'DIAG_MED_NUCL',
        nome: 'Diagnóstico por Medicina Nuclear',
        procedimentos: [
          'Cintilografia óssea com Tc-99m (3 fases)',
          'Cintilografia de tireoide com Tc-99m ou I-131',
          'Cintilografia renal com DMSA (função cortical)',
          'Cintilografia renal com DTPA (função e fluxo renal)',
          'Cintilografia de ventilação/perfusão pulmonar (TEP)',
          'Cintilografia miocárdica de perfusão (repouso e esforço)',
          'Ventriculografia radioisotópica (FEVE)',
          'PET-CT oncológico com F18-FDG (estadiamento)',
          'PET-CT cardíaco com F18-FDG (viabilidade miocárdica)',
          'PET-CT cerebral (neurologia e demências)',
          'Cintilografia de paratireoide (Sestamibi)',
          'Cintilografia hepática e de vias biliares (hepatobiliar)',
          'Cintilografia de glândulas salivares',
          'Cintilografia de sentinela (mama / melanoma)',
          'Cintilografia gástrica (esvaziamento gástrico)',
          'Cintilografia pulmonar aerosol (ventilação)',
          'Cintilografia de glândulas lacrimais',
          'Cintilografia de leucócitos marcados (infecção)',
          'Dosimetria para terapia com I-131',
          'Terapia com I-131 (hipertireoidismo / carcinoma tireoidiano)',
          'Terapia com Lu-177 (PSMA — câncer de próstata)',
          'Rastreamento corporal total com I-131',
        ],
      },
      {
        codigo: 'DIAG_ENDOSCO',
        nome: 'Diagnóstico por Endoscopia',
        procedimentos: [
          'Endoscopia digestiva alta (EDA) diagnóstica',
          'Colonoscopia diagnóstica',
          'Retossigmoidoscopia flexível',
          'Broncoscopia diagnóstica (com lavagem broncoalveolar)',
          'Laringoscopia indireta / nasofibrolaringoscopia',
          'Colangiopancreatografia retrógrada endoscópica (CPRE)',
          'Ecoendoscopia (ultrassonografia endoscópica)',
          'Cápsula endoscópica (intestino delgado)',
          'Artroscopia diagnóstica de joelho',
          'Artroscopia diagnóstica de ombro',
          'Artroscopia diagnóstica de quadril',
          'Histeroscopia diagnóstica',
          'Cistoscopia diagnóstica',
          'Ureteroscopia diagnóstica',
          'Videolaparoscopia diagnóstica',
          'Toracoscopia diagnóstica (VATS diagnóstica)',
          'Mediastinoscopia diagnóstica',
          'Rinoscopia / Nasoendoscopia diagnóstica',
          'Anosigmoidoscopia rígida',
          'Enteroscopia de duplo balão',
        ],
      },
    ],
  },

  // 2. PROCEDIMENTOS CLÍNICOS
  {
    codigo: 'CLINICO',
    nome: 'Procedimentos Clínicos',
    descricao: 'Consultas médicas e de outras profissões da saúde por especialidade',
    subCategorias: [
      { codigo: 'CLIN_MED_GERAL', nome: 'Clínica Médica / Medicina Interna', procedimentos: [
        'Consulta em clínica médica / medicina interna',
        'Consulta de segunda opinião médica',
        'Consulta para acompanhamento de doença crônica',
        'Consulta para avaliação pré-operatória',
        'Consulta para avaliação de risco cardiovascular',
      ]},
      { codigo: 'CLIN_CARDIOLOGIA', nome: 'Cardiologia', procedimentos: [
        'Consulta em cardiologia',
        'Consulta em cardiologia pediátrica',
        'Eletrocardiograma (ECG) de repouso',
        'Holter 24 horas (monitorização contínua do ritmo)',
        'MAPA — Monitorização Ambulatorial da Pressão Arterial (24h)',
        'Teste ergométrico em esteira (esforço máximo)',
        'Teste de esforço cardiopulmonar (ergoespirometria)',
        'Cateterismo cardíaco diagnóstico (coronariografia)',
        'Tilt test (teste de inclinação passiva)',
        'Implante de Holter implantável (reveal)',
        'Consulta em eletrofisiologia cardíaca',
      ]},
      { codigo: 'CLIN_ORTOPEDIA', nome: 'Ortopedia e Traumatologia', procedimentos: [
        'Consulta em ortopedia e traumatologia',
        'Consulta em ortopedia pediátrica',
        'Consulta em cirurgia da coluna vertebral',
        'Consulta em cirurgia do joelho',
        'Consulta em cirurgia do ombro',
        'Consulta em cirurgia do pé e tornozelo',
        'Consulta em cirurgia da mão',
        'Infiltração articular com corticosteroide',
        'Infiltração articular com hialuronato (viscossuplementação)',
        'Infiltração de toxina botulínica (espasticidade)',
        'Aplicação de gesso e imobilização',
        'Retirada de material de síntese (consulta)',
      ]},
      { codigo: 'CLIN_NEUROLOGIA', nome: 'Neurologia', procedimentos: [
        'Consulta em neurologia adulto',
        'Consulta em neurologia pediátrica / neuropediatria',
        'Consulta em neurologia — epilepsia',
        'Consulta em neurologia — doenças neurodegenerativas',
        'Consulta em neurologia — cefaleia / enxaqueca',
        'Consulta em neurologia — doença cerebrovascular',
        'Eletroencefalograma (EEG) convencional',
        'Vídeo-EEG (monitoramento prolongado)',
        'Eletroneuromiografia (ENMG / EMG)',
        'Potencial evocado auditivo (BERA)',
        'Potencial evocado visual (PEV)',
        'Potencial evocado somatossensorial',
        'Punção lombar (liquor) — indicação neurológica',
        'Polissonografia (estudo do sono)',
      ]},
      { codigo: 'CLIN_GINECOLOGIA', nome: 'Ginecologia e Obstetrícia', procedimentos: [
        'Consulta em ginecologia',
        'Consulta em obstetrícia (pré-natal de alto risco)',
        'Consulta em ginecologia oncológica',
        'Consulta em endoscopia ginecológica',
        'Colposcopia com biópsia',
        'Conização / LEEP (excisão de zona de transformação)',
        'Histeroscopia terapêutica (diagnóstico e tratamento)',
        'Videolaparoscopia ginecológica',
        'Colocação de DIU (dispositivo intrauterino)',
        'Consulta de planejamento familiar',
        'Mastologia — consulta e rastreamento',
      ]},
      { codigo: 'CLIN_PEDIATRIA', nome: 'Pediatria', procedimentos: [
        'Consulta em pediatria geral',
        'Consulta em neonatologia (recém-nascido)',
        'Consulta em pediatria especializada — gastroenterologia pediátrica',
        'Consulta em pediatria especializada — pneumologia pediátrica',
        'Consulta em pediatria especializada — cardiologia pediátrica',
        'Consulta em pediatria especializada — neurologia pediátrica',
        'Consulta em pediatria especializada — endocrinologia pediátrica',
        'Consulta em pediatria especializada — reumatologia pediátrica',
        'Consulta em pediatria especializada — oncologia pediátrica',
        'Consulta em pediatria especializada — nefrologia pediátrica',
        'Consulta em pediatria especializada — infectologia pediátrica',
        'Avaliação do desenvolvimento infantil (triagem)',
      ]},
      { codigo: 'CLIN_PSIQUIATRIA', nome: 'Psiquiatria', procedimentos: [
        'Consulta em psiquiatria adulto',
        'Consulta em psiquiatria infantojuvenil',
        'Consulta em psiquiatria — dependência química',
        'Consulta em psiquiatria — transtorno do espectro autista (TEA)',
        'Consulta em psiquiatria — transtorno de humor (depressão / bipolar)',
        'Avaliação psiquiátrica para fins de perícia / laudo',
      ]},
      { codigo: 'CLIN_DERMATOLOGIA', nome: 'Dermatologia', procedimentos: [
        'Consulta em dermatologia',
        'Consulta em dermatologia oncológica (rastreamento de melanoma)',
        'Consulta em dermatologia — doenças inflamatórias (psoríase, lúpus cutâneo)',
        'Consulta em alergologia / imunologia clínica',
        'Dermoscopia (dermatoscopia)',
        'Teste de contato (patch test)',
        'Teste alérgico intradérmico',
        'Fototerapia UVB banda estreita (NB-UVB)',
        'PUVA (fototerapia com psoraleno)',
      ]},
      { codigo: 'CLIN_OFTALMOLOGIA', nome: 'Oftalmologia', procedimentos: [
        'Consulta em oftalmologia',
        'Consulta em oftalmologia pediátrica',
        'Campimetria visual computadorizada (campo visual)',
        'Retinografia colorida (fundo de olho)',
        'Angiofluoresceinografia (AFG)',
        'OCT — tomografia de coerência óptica (retina / nervo)',
        'Paquimetria corneana',
        'Topografia corneana (ceratometria computadorizada)',
        'Tonometria (pressão intraocular)',
        'Biometria ocular (cálculo de lente intraocular)',
        'Eletrorretinograma (ERG)',
        'Potencial evocado visual cortical',
        'Consulta em estrabismo e motilidade ocular',
        'Consulta em glaucoma',
        'Consulta em retina e vítreo',
        'Aplicação de laser (YAG / fotocoagulação)',
      ]},
      { codigo: 'CLIN_OTORRINO', nome: 'Otorrinolaringologia', procedimentos: [
        'Consulta em otorrinolaringologia',
        'Audiometria tonal limiar e vocal',
        'Audiometria de tronco cerebral (BERA / ABR)',
        'Emissões otoacústicas (EOA)',
        'Imitanciometria (timpanometria)',
        'Vestibulometria (VNG / vectoeletronistagmografia)',
        'Potencial evocado miogênico vestibular (VEMP)',
        'Nasofibrolaringoscopia (videoendoscopia)',
        'Laringoscopia direta',
        'Videolaringostroboscopia',
        'Teste de função nasal (rinomanometria)',
        'Polissonografia (apneia do sono)',
        'Consulta em audiologia clínica',
        'Consulta em doenças do equilíbrio (otoneurologia)',
      ]},
      { codigo: 'CLIN_UROLOGIA', nome: 'Urologia', procedimentos: [
        'Consulta em urologia',
        'Consulta em urologia pediátrica',
        'Consulta em uroginecologia',
        'Consulta em andrologia',
        'Urodinâmica completa (estudo urodinâmico)',
        'Fluxometria urinária',
        'Eletroestimulação do assoalho pélvico',
        'Consulta em oncologia urológica',
      ]},
      { codigo: 'CLIN_ENDOCRINOLOGIA', nome: 'Endocrinologia', procedimentos: [
        'Consulta em endocrinologia e metabologia',
        'Consulta em diabetologia',
        'Consulta em endocrinologia pediátrica',
        'Consulta em tireoide e paratireoide',
        'Consulta em obesidade e cirurgia bariátrica (pré-operatório)',
        'Consulta em disfunções hipofisárias',
        'Consulta em doenças adrenais',
      ]},
      { codigo: 'CLIN_REUMATOLOGIA', nome: 'Reumatologia', procedimentos: [
        'Consulta em reumatologia',
        'Consulta em reumatologia pediátrica',
        'Consulta em lúpus eritematoso sistêmico (LES)',
        'Consulta em artrite reumatoide',
        'Consulta em fibromialgia',
        'Consulta em espondiloartropatias',
        'Consulta em osteoporose',
      ]},
      { codigo: 'CLIN_GASTRO', nome: 'Gastroenterologia', procedimentos: [
        'Consulta em gastroenterologia',
        'Consulta em hepatologia',
        'Consulta em proctologia',
        'Consulta em gastroenterologia pediátrica',
        'Consulta em doenças inflamatórias intestinais (DII)',
        'Consulta em transplante hepático (pré e pós)',
        'Manometria esofágica de alta resolução',
        'pHmetria esofágica de 24 horas',
        'Manometria anorretal',
      ]},
      { codigo: 'CLIN_PNEUMOLOGIA', nome: 'Pneumologia', procedimentos: [
        'Consulta em pneumologia',
        'Consulta em pneumologia pediátrica',
        'Consulta em pneumologia — asma e DPOC',
        'Consulta em medicina do sono',
        'Espirometria com broncodilatador (prova de função pulmonar)',
        'Teste de broncoprovocação (metacolina)',
        'Teste de caminhada de 6 minutos',
        'Oximetria noturna',
        'Titulação de CPAP (ajuste de pressão)',
        'Consulta em oncologia torácica',
      ]},
      { codigo: 'CLIN_NEFROLOGIA', nome: 'Nefrologia', procedimentos: [
        'Consulta em nefrologia',
        'Consulta em nefrologia pediátrica',
        'Consulta em transplante renal (pré e pós)',
        'Consulta em diálise e terapia renal substitutiva',
        'Consulta em hipertensão arterial resistente',
      ]},
      { codigo: 'CLIN_HEMATOLOGIA', nome: 'Hematologia e Hemoterapia', procedimentos: [
        'Consulta em hematologia adulto',
        'Consulta em hematologia pediátrica',
        'Consulta em coagulopatias',
        'Consulta em hemoglobinopatias (anemia falciforme)',
        'Consulta em oncohematologia',
        'Consulta em transplante de medula óssea',
      ]},
      { codigo: 'CLIN_ONCOLOGIA', nome: 'Oncologia', procedimentos: [
        'Consulta em oncologia clínica adulto',
        'Consulta em oncologia pediátrica',
        'Consulta em radioterapia',
        'Consulta em oncologia cirúrgica',
        'Consulta em cuidados paliativos',
        'Consulta de apoio psicológico em oncologia',
        'Consulta em oncologia — mama',
        'Consulta em oncologia — pulmão',
        'Consulta em oncologia — cólon e reto',
        'Consulta em oncologia — próstata',
        'Consulta em oncologia — cabeça e pescoço',
        'Consulta em oncologia — hematológica',
      ]},
      { codigo: 'CLIN_FISIOTERAPIA', nome: 'Fisioterapia', procedimentos: [
        'Fisioterapia respiratória (reabilitação pulmonar)',
        'Fisioterapia neurológica adulto (AVC, TCE, Parkinson)',
        'Fisioterapia neurológica infantil (PC, mielomeningocele)',
        'Fisioterapia ortopédica e traumatológica',
        'Fisioterapia em uroginecologia (assoalho pélvico)',
        'Fisioterapia cardiovascular (reabilitação cardíaca)',
        'Fisioterapia oncológica (drenagem linfática pós-mastectomia)',
        'Hidroterapia (fisioterapia aquática)',
        'RPG — Reeducação Postural Global',
        'Acupuntura fisioterápica',
        'Pilates clínico / terapêutico',
        'Fisioterapia em UTI (fisioterapia intensiva)',
        'Fisioterapia reumatológica',
        'Terapia manual e osteopatia',
        'Fisioterapia pediátrica geral',
      ]},
      { codigo: 'CLIN_PSICOLOGIA', nome: 'Psicologia', procedimentos: [
        'Psicoterapia individual adulto',
        'Psicoterapia individual infantojuvenil',
        'Avaliação psicológica / neuropsicológica',
        'Psicoterapia em grupo (adultos)',
        'Psicoterapia em grupo (adolescentes)',
        'Orientação / terapia familiar',
        'Orientação parental',
        'Psicologia em saúde oncológica',
        'Psicologia em reabilitação',
        'Psicologia em saúde da mulher',
        'Avaliação neuropsicológica (demências)',
        'Psicologia em dependência química',
      ]},
      { codigo: 'CLIN_NUTRICAO', nome: 'Nutrição e Dietética', procedimentos: [
        'Consulta em nutrição clínica adulto',
        'Consulta em nutrição pediátrica',
        'Acompanhamento nutricional em doenças crônicas (diabetes, HAS)',
        'Consulta nutricional em obesidade e emagrecimento',
        'Nutrição em oncologia',
        'Nutrição em doenças renais (nefrologia)',
        'Nutrição em doenças hepáticas (hepatologia)',
        'Nutrição em doenças inflamatórias intestinais',
        'Nutrição em distúrbios alimentares (anorexia, bulimia)',
        'Suporte nutricional enteral e parenteral (ambulatorial)',
        'Nutrição gestacional e lactação',
        'Nutrição esportiva',
      ]},
      { codigo: 'CLIN_FARMACIA', nome: 'Assistência Farmacêutica', procedimentos: [
        'Consulta farmacêutica (atenção farmacêutica individualizada)',
        'Revisão da farmacoterapia (reconciliação medicamentosa)',
        'Dispensação de medicamentos especiais — CEAF (Componente Especializado)',
        'Orientação ao uso racional de medicamentos',
        'Acompanhamento farmacoterapêutico em doenças crônicas',
        'Consulta farmacêutica em anticoagulação',
        'Consulta farmacêutica oncológica (quimioterapia oral)',
        'Dispensação de insumos para diabetes (tiras, seringas)',
      ]},
      { codigo: 'CLIN_FONOAUDIOLOGIA', nome: 'Fonoaudiologia', procedimentos: [
        'Avaliação fonoaudiológica completa',
        'Terapia de linguagem oral infantil (atraso, gagueira)',
        'Terapia de linguagem escrita (dislexia)',
        'Terapia de voz (disfonia, nódulos vocais)',
        'Terapia de deglutição (disfagia — adulto)',
        'Terapia de deglutição (disfagia — pediátrica)',
        'Reabilitação auditiva e adaptação de AASI (aparelho auditivo)',
        'Terapia para TEA (transtorno do espectro autista) — comunicação',
        'Fonoaudiologia hospitalar / intensiva',
        'Fonoaudiologia em gerontologia (idosos)',
        'Terapia miofuncional orofacial',
      ]},
      { codigo: 'CLIN_TO', nome: 'Terapia Ocupacional', procedimentos: [
        'Avaliação em terapia ocupacional',
        'Terapia ocupacional neurológica adulto (pós-AVC, lesão medular)',
        'Terapia ocupacional neurológica infantil (PC, atraso)',
        'Terapia ocupacional em saúde mental',
        'Terapia ocupacional pediátrica (integração sensorial)',
        'Terapia ocupacional em mão e membro superior',
        'Confecção de órteses (talas) e adaptações',
        'Terapia ocupacional em reabilitação oncológica',
        'Terapia ocupacional em geriatria (idosos)',
      ]},
      { codigo: 'CLIN_ASSISTENCIA_SOC', nome: 'Serviço Social em Saúde', procedimentos: [
        'Atendimento em serviço social em saúde (avaliação socioeconômica)',
        'Visita domiciliar social',
        'Orientação de benefícios previdenciários e sociais (LOAS, BPC)',
        'Encaminhamento e articulação de rede de proteção social',
        'Atendimento em situações de violência e vulnerabilidade',
        'Orientação familiar e suporte psicossocial',
        'Acompanhamento de alta hospitalar complexa',
      ]},
    ],
  },

  // 3. PROCEDIMENTOS CIRÚRGICOS
  {
    codigo: 'CIRURGICO',
    nome: 'Procedimentos Cirúrgicos',
    descricao: 'Intervenções cirúrgicas eletivas, de pequeno porte e de urgência',
    subCategorias: [
      {
        codigo: 'CIR_PEQUENA',
        nome: 'Pequenas Cirurgias e Procedimentos Ambulatoriais',
        procedimentos: [
          'Exérese de tumor / cisto cutâneo benigno',
          'Exérese de lipoma',
          'Exérese de nevus (nevo) melanocítico',
          'Biópsia excisional de pele e subcutâneo',
          'Sutura de ferida complexa / laceração extensa',
          'Drenagem de abscesso cutâneo',
          'Drenagem de hematoma',
          'Cauterização de lesão cutânea (química elétrica)',
          'Remoção de corpo estranho superficial',
          'Ungectomia (retirada de unha encravada)',
          'Frenectomia lingual ou labial',
          'Vasectomia (ligadura de deferentes)',
          'Laqueadura tubária eletiva ambulatorial',
          'Circuncisão / postectomia',
          'Herniorrafia inguinal ambulatorial (pequeno porte)',
          'Hemorroidectomia ambulatorial (ligadura elástica / escleroterapia)',
          'Fistulotomia anal ambulatorial',
          'Polipectomia endoscópica (cólon)',
          'Mucosectomia endoscópica (EMR)',
          'Hemostasia endoscópica (varizes esofágicas, úlcera)',
          'Dilatação esofágica endoscópica',
          'Colostomia / ileostomia de alça (pequeno porte)',
          'Retirada de DIU (com dificuldade)',
          'Biópsia de endométrio (curetagem diagnóstica)',
          'Cauterização cervical (crioterapia / laser)',
          'Infiltração de toxina botulínica (hiperidrose / espasticidade)',
          'Desbridamento cirúrgico de ferida crônica / úlcera',
          'Enxerto de pele (pequena área)',
          'Exérese de lesão labial, oral',
          'Pequena cirurgia de mão (cisto sinovial, dedo em gatilho)',
          'Pleuroscopia / biopsia pleural às cegas',
          'Toracocentese (drenagem de líquido pleural)',
          'Paracentese abdominal terapêutica',
          'Punção lombar terapêutica',
          'Implante de cateter Port-a-Cath / PICC',
          'Retirada de cateter venoso central implantável',
          'Traqueostomia ambulatorial eletiva',
          'Gastrostomia endoscópica percutânea (PEG)',
          'Cistostomia percutânea (punção suprapúbica)',
          'Nefrostomia percutânea',
          'Colocação de cateter duplo J ureteral',
          'Colocação de dreno de tímpano (paracentese do tímpano)',
          'Amigdalectomia ambulatorial (adulto simples)',
          'Septoplastia ambulatorial',
          'Cirurgia da síndrome do túnel do carpo',
          'Procedimento para ingurgitamento venoso (varizes, escleroterapia)',
        ],
      },
      {
        codigo: 'CIR_ELETIVA',
        nome: 'Cirurgias Eletivas',
        procedimentos: [
          'Colecistectomia videolaparoscópica',
          'Colecistectomia convencional (aberta)',
          'Herniorrafia inguinal / femoral (laparoscópica ou aberta)',
          'Herniorrafia umbilical',
          'Herniorrafia incisional / eventração',
          'Apendicectomia eletiva (laparoscópica)',
          'Fundoplicatura (cirurgia anti-refluxo — Nissen / Toupet)',
          'Gastrectomia parcial (úlcera, tumor)',
          'Gastrectomia total (oncológica)',
          'Cirurgia bariátrica — bypass gástrico (Roux-en-Y)',
          'Cirurgia bariátrica — gastrectomia vertical (sleeve)',
          'Colectomia direita / esquerda (laparoscópica ou aberta)',
          'Colectomia total / proctocolectomia',
          'Retissigmoidectomia com anastomose',
          'Cirurgia de Hartmann',
          'Cirurgia proctológica — hemorroidectomia convencional (Ferguson / Milligan)',
          'Cirurgia de fístula anorretal',
          'Operação de Bassini / Shouldice (hérnias complexas)',
          'Esplenectomia',
          'Adrenalectomia',
          'Hepatectomia parcial (ressecção hepática)',
          'Colangioentero anastomose (derivação biliodigestiva)',
          'Duodenopancreatectomia (Whipple)',
          'Pancreatectomia corpo e cauda',
          'Ressecção pulmonar (lobectomia / segmentectomia) — VATS',
          'Pneumonectomia',
          'Ressecção de tumor mediastinal',
          'Correção de pectus excavatum',
          'Mastectomia parcial (tumorectomia / quadrantectomia)',
          'Mastectomia radical modificada',
          'Reconstrução mamária (expansor / TRAM / implante)',
          'Cirurgia de redução mamária',
          'Histerectomia total abdominal',
          'Histerectomia vaginal',
          'Histerectomia laparoscópica',
          'Miomectomia (laparoscópica ou aberta)',
          'Salpingooforectomia unilateral ou bilateral',
          'Videolaparoscopia ginecológica terapêutica (endometriose)',
          'Correção de prolapso genital (colpoperineoplastia)',
          'Sling suburetral (incontinência urinária de esforço)',
          'Prostatectomia radical (laparoscópica / robótica)',
          'Prostatectomia transuretral (RTU-P)',
          'Nefrectomia radical ou parcial',
          'Cistectomia parcial ou total',
          'Ureteroscopia terapêutica com litotripsia',
          'Nefrolitotripsia percutânea (NLPC)',
          'Litotripsia extracorpórea por onda de choque (LECO)',
          'Orquiectomia radical',
          'Varicocelectomia',
          'Correção de hipospádia',
          'Correção de fimose infantil (pré-púcio)',
          'Artroplastia total de quadril (PTQ)',
          'Artroplastia total de joelho (PTJ)',
          'Artroscopia terapêutica de joelho (menisco, LCA)',
          'Artroscopia terapêutica de ombro (manguito)',
          'Osteossíntese de fraturas (placa, parafuso, haste)',
          'Retirada de material de síntese',
          'Artrodese de coluna (fusão vertebral)',
          'Discectomia por via minimamente invasiva',
          'Laminectomia descompressiva',
          'Cirurgia do pé (joanete — hallux valgus)',
          'Correção de pé torto congênito',
          'Cirurgia do nervo periférico',
          'Craniotomia para ressecção de tumor cerebral',
          'Cirurgia endoscópica de tumor hipofisário',
          'Derivação ventricular peritoneal (DVP — hidrocefalia)',
          'Clipagem de aneurisma cerebral (eletivo)',
          'Microcirurgia de hérnia de disco (lombar / cervical)',
          'Neurocirurgia de epilepsia',
          'Estimulação cerebral profunda (deep brain stimulation)',
          'Tireoidectomia total ou parcial',
          'Paratireoidectomia',
          'Esvaziamento cervical ganglionar',
          'Amigdalectomia e/ou adenoidectomia convencional',
          'Septoplastia com turbinoplastia',
          'Cirurgia endoscópica nasal sinusal (FESS)',
          'Timpanoplastia e mastoidectomia',
          'Implante coclear',
          'Estapedectomia (otosclerose)',
          'Revascularização miocárdica (ponte de safena / CABG)',
          'Cirurgia valvar cardíaca (troca / plastia)',
          'Correção de aneurisma de aorta',
          'Safenectomia / cirurgia de varizes de membros inferiores',
          'Endoprótese vascular (EVAR / TEVAR)',
          'Transplante renal',
          'Transplante hepático',
          'Transplante cardíaco',
          'Transplante pulmonar',
          'Transplante de medula óssea (alogênico / autólogo)',
          'Transplante de córnea',
          'Facoemulsificação com implante de LIO (catarata)',
          'Vitrectomia posterior',
          'Cirurgia de glaucoma (trabeculectomia)',
          'Correção de descolamento de retina',
          'Correção de estrabismo',
          'Blefaroplastia funcional (ptose)',
          'Correção de pterígio com transplante conjuntival',
          'Cirurgia de queimaduras (enxertia)',
          'Correção de cicatrizes',
          'Cirurgia de lábio leporino / fenda palatina',
          'Cirurgia craniofacial',
        ],
      },
      {
        codigo: 'CIR_URGENCIA',
        nome: 'Cirurgias de Urgência e Emergência',
        procedimentos: [
          'Laparotomia exploradora de urgência',
          'Apendicectomia de urgência (apendicite aguda)',
          'Colecistectomia de urgência (colecistite aguda)',
          'Herniorrafia de urgência (estrangulamento)',
          'Cirurgia de trauma abdominal (lesão de vísceras)',
          'Cirurgia de trauma torácico (hemotórax, pneumotórax)',
          'Cirurgia de trauma cranioencefálico (TCE grave)',
          'Craniotomia de urgência (hematoma epidural / subdural)',
          'Clipagem de urgência de aneurisma roto',
          'Hemicraniectomia descompressiva (AVC isquêmico maligno)',
          'Cirurgia de trauma vascular (lesão arterial / venosa)',
          'Tromboembolectomia arterial de urgência',
          'Embolectomia pulmonar cirúrgica (TEP maciço)',
          'Pericardiocentese / janela pericárdica de urgência',
          'Cirurgia cardíaca de urgência (tamponamento, ruptura)',
          'Angioplastia / revascularização de urgência (IAM)',
          'Cesariana de urgência / parto operatório',
          'Cirurgia para gravidez ectópica rota',
          'Cirurgia para rotura de cisto ovariano / torção anexial',
          'Orquipexia de urgência (torção testicular)',
          'Cirurgia de priapismo de urgência',
          'Traqueostomia de urgência (via aérea comprometida)',
          'Cricotireoidotomia de emergência',
          'Drenagem de hemotórax / pneumotórax (toracostomia)',
          'Drenagem cirúrgica de abscesso profundo (cervical, abdominal)',
          'Amputação de urgência (trauma, isquemia irreversível)',
          'Fasciotomia (síndrome compartimental)',
          'Cirurgia ortopédica de urgência (fratura exposta, luxação)',
          'Laparostomia (abdome aberto — controle de dano)',
          'Cirurgia de úlcera péptica perfurada',
          'Colostomia de urgência (obstrução intestinal maligna)',
          'Cirurgia de megacólon tóxico (colite grave)',
          'Nefrectomia de urgência (ruptura / sangramento renal)',
          'Drenagem de empiema pleural (toracotomia)',
          'Reimplante de extremidade / dedo traumatizado',
        ],
      },
    ],
  },
];

// ─── Função principal de seed ──────────────────────────────────────────────

async function main() {
  console.log('🌱 Iniciando seed de procedimentos — Regulação Assistencial...\n');

  let totalCategorias = 0;
  let totalSubCategorias = 0;
  let totalProcedimentos = 0;

  for (const categoria of SEED_DATA) {
    // Upsert da categoria principal
    const catDb = await prisma.categoriaProcedimento.upsert({
      where: { codigo: categoria.codigo },
      update: { nome: categoria.nome, descricao: categoria.descricao },
      create: {
        codigo:    categoria.codigo,
        nome:      categoria.nome,
        descricao: categoria.descricao,
      },
    });
    totalCategorias++;
    console.log(`✅ Categoria: ${catDb.nome}`);

    for (const sub of categoria.subCategorias) {
      // Upsert da subcategoria
      const subDb = await prisma.subCategoriaProcedimento.upsert({
        where: { codigo: sub.codigo },
        update: { nome: sub.nome, categoriaId: catDb.id },
        create: {
          codigo:      sub.codigo,
          nome:        sub.nome,
          categoriaId: catDb.id,
        },
      });
      totalSubCategorias++;
      console.log(`   ├─ Subcategoria: ${subDb.nome} (${sub.procedimentos.length} procedimentos)`);

      // Upsert de cada procedimento
      for (const nomeProcedimento of sub.procedimentos) {
        // Chave de idempotência: nome + subCategoriaId
        const existing = await prisma.procedimento.findFirst({
          where: { nome: nomeProcedimento, subCategoriaId: subDb.id },
        });

        if (!existing) {
          await prisma.procedimento.create({
            data: {
              nome:          nomeProcedimento,
              subCategoriaId: subDb.id,
              ativo:         true,
            },
          });
        }
        totalProcedimentos++;
      }
    }

    console.log('');
  }

  console.log('─'.repeat(60));
  console.log(`✔  Categorias:     ${totalCategorias}`);
  console.log(`✔  Subcategorias:  ${totalSubCategorias}`);
  console.log(`✔  Procedimentos:  ${totalProcedimentos}`);
  console.log('─'.repeat(60));
  console.log('🎉 Seed concluído com sucesso!\n');
}

main()
  .catch((e) => {
    console.error('❌ Erro no seed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
